version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nestjs:
    build:
      context: .
    container_name: mongoDB_microservice
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/users_linkedin_clone

volumes:
  mongo_data:
