services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: microservice_users
      POSTGRES_USER: jeffersons
      POSTGRES_PASSWORD: 'JFS0211@ti'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: